export interface Product {
  id: string;
  name: string;
  nameUz?: string;
  category: string;
  price: number;
  originalPrice?: number;
  unit: string;
  image: string;
  badge?: "sale" | "new" | "hot";
  rating: number;
  description: string;
  brand?: string;
  weight?: string;
  inStock: boolean;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  color: string;
  bgColor: string;
  count: number;
}

export const CATEGORIES: Category[] = [
  { id: "fruits", name: "Fruits", icon: "nutrition", color: "#FF6B35", bgColor: "#FFF0EB", count: 24 },
  { id: "vegetables", name: "Vegetables", icon: "leaf", color: "#1A9B5C", bgColor: "#E8F5EE", count: 31 },
  { id: "dairy", name: "Dairy", icon: "water", color: "#3B82F6", bgColor: "#EFF6FF", count: 18 },
  { id: "meat", name: "Meat", icon: "flame", color: "#EF4444", bgColor: "#FEF2F2", count: 22 },
  { id: "bakery", name: "Bakery", icon: "cafe", color: "#F59E0B", bgColor: "#FFFBEB", count: 14 },
  { id: "beverages", name: "Drinks", icon: "wine", color: "#8B5CF6", bgColor: "#F5F3FF", count: 29 },
  { id: "snacks", name: "Snacks", icon: "pizza", color: "#EC4899", bgColor: "#FDF2F8", count: 20 },
  { id: "frozen", name: "Frozen", icon: "snow", color: "#06B6D4", bgColor: "#ECFEFF", count: 16 },
];

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Banana",
    category: "fruits",
    price: 3500,
    unit: "kg",
    image: "🍌",
    badge: "hot",
    rating: 4.8,
    description: "Fresh ripe bananas from Ecuador. Sweet, nutritious and perfect for smoothies or snacking.",
    brand: "FreshFarm",
    weight: "1 kg",
    inStock: true,
  },
  {
    id: "2",
    name: "Red Apple",
    category: "fruits",
    price: 8900,
    originalPrice: 11000,
    unit: "kg",
    image: "🍎",
    badge: "sale",
    rating: 4.6,
    description: "Crispy and sweet red apples. Rich in vitamins and antioxidants.",
    brand: "Garden Fresh",
    weight: "1 kg",
    inStock: true,
  },
  {
    id: "3",
    name: "Tomato",
    category: "vegetables",
    price: 4500,
    unit: "kg",
    image: "🍅",
    rating: 4.7,
    description: "Vine-ripened tomatoes with rich flavor. Perfect for salads and cooking.",
    brand: "Local Farm",
    weight: "1 kg",
    inStock: true,
  },
  {
    id: "4",
    name: "Fresh Milk",
    category: "dairy",
    price: 7500,
    unit: "L",
    image: "🥛",
    badge: "new",
    rating: 4.9,
    description: "Farm-fresh whole milk. Rich in calcium and protein, perfect for the whole family.",
    brand: "DairyBest",
    weight: "1 L",
    inStock: true,
  },
  {
    id: "5",
    name: "Chicken Breast",
    category: "meat",
    price: 32000,
    originalPrice: 38000,
    unit: "kg",
    image: "🍗",
    badge: "sale",
    rating: 4.7,
    description: "Lean chicken breast, hormone-free and antibiotic-free. Perfect for healthy meals.",
    brand: "FreshMeat Co.",
    weight: "1 kg",
    inStock: true,
  },
  {
    id: "6",
    name: "White Bread",
    category: "bakery",
    price: 6500,
    unit: "pcs",
    image: "🍞",
    rating: 4.5,
    description: "Freshly baked white bread. Soft texture with golden crust.",
    brand: "Bakehouse",
    weight: "500 g",
    inStock: true,
  },
  {
    id: "7",
    name: "Orange Juice",
    category: "beverages",
    price: 15000,
    unit: "L",
    image: "🍊",
    rating: 4.8,
    description: "100% natural squeezed orange juice. No added sugar or preservatives.",
    brand: "SunFresh",
    weight: "1 L",
    inStock: true,
  },
  {
    id: "8",
    name: "Potato",
    category: "vegetables",
    price: 3200,
    unit: "kg",
    image: "🥔",
    rating: 4.6,
    description: "Fresh local potatoes. Great for frying, boiling, or baking.",
    brand: "Local Farm",
    weight: "1 kg",
    inStock: true,
  },
  {
    id: "9",
    name: "Yogurt",
    category: "dairy",
    price: 5500,
    unit: "pcs",
    image: "🫙",
    badge: "new",
    rating: 4.7,
    description: "Creamy Greek-style yogurt. High protein, probiotic-rich.",
    brand: "DairyBest",
    weight: "400 g",
    inStock: true,
  },
  {
    id: "10",
    name: "Watermelon",
    category: "fruits",
    price: 4800,
    unit: "kg",
    image: "🍉",
    badge: "hot",
    rating: 4.9,
    description: "Sweet and juicy summer watermelon. Refreshing and hydrating.",
    brand: "Summer Farm",
    weight: "1 kg",
    inStock: true,
  },
  {
    id: "11",
    name: "Eggs",
    category: "dairy",
    price: 18000,
    unit: "dozen",
    image: "🥚",
    rating: 4.8,
    description: "Farm-fresh free-range eggs. High quality protein source.",
    brand: "Happy Hen",
    weight: "12 pcs",
    inStock: true,
  },
  {
    id: "12",
    name: "Carrot",
    category: "vegetables",
    price: 3800,
    unit: "kg",
    image: "🥕",
    rating: 4.6,
    description: "Fresh crispy carrots. Rich in vitamins A and C.",
    brand: "Garden Fresh",
    weight: "1 kg",
    inStock: true,
  },
  {
    id: "13",
    name: "Ground Beef",
    category: "meat",
    price: 45000,
    unit: "kg",
    image: "🥩",
    rating: 4.7,
    description: "Fresh lean ground beef. Perfect for burgers, meatballs and more.",
    brand: "FreshMeat Co.",
    weight: "1 kg",
    inStock: true,
  },
  {
    id: "14",
    name: "Cola",
    category: "beverages",
    price: 9500,
    originalPrice: 12000,
    unit: "L",
    image: "🥤",
    badge: "sale",
    rating: 4.5,
    description: "Classic refreshing cola. Chilled and ready to drink.",
    brand: "RefreshCo",
    weight: "2 L",
    inStock: true,
  },
  {
    id: "15",
    name: "Chips",
    category: "snacks",
    price: 7200,
    unit: "pcs",
    image: "🥨",
    rating: 4.4,
    description: "Crunchy golden chips with light seasoning.",
    brand: "CrunchTime",
    weight: "200 g",
    inStock: true,
  },
  {
    id: "16",
    name: "Butter",
    category: "dairy",
    price: 12500,
    unit: "pcs",
    image: "🧈",
    rating: 4.8,
    description: "Creamy natural butter. Made from fresh cream.",
    brand: "DairyBest",
    weight: "200 g",
    inStock: true,
  },
  {
    id: "17",
    name: "Cucumber",
    category: "vegetables",
    price: 3500,
    unit: "kg",
    image: "🥒",
    rating: 4.6,
    description: "Fresh crunchy cucumbers. Perfect for salads.",
    brand: "Local Farm",
    weight: "1 kg",
    inStock: true,
  },
  {
    id: "18",
    name: "Mango",
    category: "fruits",
    price: 12000,
    unit: "kg",
    image: "🥭",
    badge: "new",
    rating: 4.8,
    description: "Sweet tropical mangoes, freshly imported. A tropical delight.",
    brand: "Tropical Fresh",
    weight: "1 kg",
    inStock: true,
  },
  {
    id: "19",
    name: "Mineral Water",
    category: "beverages",
    price: 3500,
    unit: "L",
    image: "💧",
    rating: 4.9,
    description: "Pure mountain mineral water. Naturally refreshing.",
    brand: "AquaPure",
    weight: "1.5 L",
    inStock: true,
  },
  {
    id: "20",
    name: "Ice Cream",
    category: "frozen",
    price: 8500,
    unit: "pcs",
    image: "🍦",
    badge: "hot",
    rating: 4.9,
    description: "Creamy vanilla ice cream. Made with real dairy.",
    brand: "FrozenDelights",
    weight: "500 ml",
    inStock: true,
  },
];

export const BANNERS = [
  {
    id: "1",
    title: "Fresh Fruits\nDelivered Daily",
    subtitle: "Up to 30% off",
    color: "#1A9B5C",
    lightColor: "#2ECC71",
    emoji: "🍓",
  },
  {
    id: "2",
    title: "Meat & Poultry\nSpecial Deals",
    subtitle: "Starting from 32,000 UZS",
    color: "#E53E3E",
    lightColor: "#FC8181",
    emoji: "🥩",
  },
  {
    id: "3",
    title: "Dairy Products\nEvery Day Fresh",
    subtitle: "Free delivery over 100k",
    color: "#2B6CB0",
    lightColor: "#63B3ED",
    emoji: "🥛",
  },
];

export function formatPrice(price: number): string {
  return price.toLocaleString("ru-RU") + " UZS";
}
