export const SUBCATEGORY_IMAGES: Record<string, any> = {
  "sub-mevalar": require("@/assets/subcategory-images/sub-mevalar.png"),
  "sub-sabzavotlar": require("@/assets/subcategory-images/sub-sabzavotlar.png"),
  "sub-non": require("@/assets/subcategory-images/sub-non.png"),
  "sub-konserva": require("@/assets/subcategory-images/sub-konserva.png"),
  "sub-gosht": require("@/assets/subcategory-images/sub-gosht.png"),
  "sub-murabbo": require("@/assets/subcategory-images/sub-murabbo.png"),
  "sub-coffee": require("@/assets/subcategory-images/sub-coffee.png"),
  "sub-energetik": require("@/assets/subcategory-images/sub-energetik.png"),
  "sub-sharbatlar": require("@/assets/subcategory-images/sub-sharbatlar.png"),
  "sub-kolbasa": require("@/assets/subcategory-images/sub-kolbasa.png"),
  "sub-pishloq": require("@/assets/subcategory-images/sub-pishloq.png"),
  "sub-qatiq": require("@/assets/subcategory-images/sub-qatiq.png"),
  "sub-tuxum": require("@/assets/subcategory-images/sub-tuxum.png"),
  "sub-yogurt": require("@/assets/subcategory-images/sub-yogurt.png"),
  "sub-choy": require("@/assets/subcategory-images/sub-choy.png"),
  "sub-coffee-cat": require("@/assets/subcategory-images/sub-coffee-cat.png"),
  "sub-ketchup": require("@/assets/subcategory-images/sub-ketchup.png"),
  "sub-makaron": require("@/assets/subcategory-images/sub-makaron.png"),
  "sub-mayonez": require("@/assets/subcategory-images/sub-mayonez.png"),
  "sub-sharbat-cat": require("@/assets/subcategory-images/sub-sharbat-cat.png"),
  "sub-shokolad": require("@/assets/subcategory-images/sub-shokolad.png"),
  "sub-pasta": require("@/assets/subcategory-images/sub-pasta.png"),
  "sub-yog": require("@/assets/subcategory-images/sub-yog.png"),
  "sub-sneklar": require("@/assets/subcategory-images/sub-sneklar.png"),
  "sub-shampun": require("@/assets/subcategory-images/sub-shampun.png"),
  "sub-taglik": require("@/assets/subcategory-images/sub-taglik.png"),
};
